CREATE TABLE IF NOT EXISTS logistics_deliveries (
  order_id VARCHAR(20) PRIMARY KEY,
  order_date DATE,
  region VARCHAR(50),
  city VARCHAR(100),
  customer_lat DECIMAL(9,6),
  customer_lon DECIMAL(9,6),
  depot_id VARCHAR(20),
  depot_lat DECIMAL(9,6),
  depot_lon DECIMAL(9,6),
  vehicle_id_planned VARCHAR(20),
  priority VARCHAR(20),
  package_weight_kg DECIMAL(10,2),
  service_time_min INT,
  time_window_start TIME,
  time_window_end TIME,
  distance_km_est DECIMAL(10,2),
  traffic_factor DECIMAL(5,2),
  travel_time_min_est DECIMAL(10,1),
  delivery_duration_min_est DECIMAL(10,1),
  delivered_late BOOLEAN,
  fuel_cost_est DECIMAL(10,2),
  co2_kg_est DECIMAL(10,2),
  status VARCHAR(20),
  INDEX idx_date_city (order_date, city),
  INDEX idx_region (region),
  INDEX idx_depot (depot_id)
);
